### ISSUE TITLE
Failed to read ftherland

### ISSUE THREAD

**Issue by Moggers** [ReversingSpace/dominions4.gamedata#1]
Failed to read fatherland readerror: failed to read header: signature (inner: EOF)
Dumping to file /root/.blitzbackend/logs/ftherland.log
I'm gonna check if the ftherland has a valid turn number and then keep going if it does...
It's fucked, I want something over 0, instead I got 0
Failed to read fatherland fatherland: sentinel-like value must exceed 4474 and does not (is 1)
Dumping to file /root/.blitzbackend/logs/ftherland.log
I'm gonna check if the ftherland has a valid turn number and then keep going if it does...
Looks good, I want something over 0, and I got 14
13, 14
0xfe5e [252 249 242 229 203 151 47 94]
0xfe5e [252 249 242 229 203 151 47 94]
Failed to send email about game Test Email Again, 535 5.7.8 Error: authentication failed: , []string{"xxx@gmail.com", "xxx@gmail.com"}
Failed to read fatherland fatherland: sentinel-like value must exceed 4474 and does not (is 1)
Dumping to file /root/.blitzbackend/logs/ftherland.log
I'm gonna check if the ftherland has a valid turn number and then keep going if it does...
Looks good, I want something over 0, and I got 14
14, 14
Failed to read fatherland fatherland: sentinel-like value must exceed 4474 and does not (is 1)
Dumping to file /root/.blitzbackend/logs/ftherland.log
I'm gonna check if the ftherland has a valid turn number and then keep going if it does...
Looks good, I want something over 0, and I got 14
14, 14

**Comment by Moggers** [comment]
goroutine 37 [running]:
panic(0x8721e0, 0xc8203ce300)
        /usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/ReversingSpace/dominions4.gamedata/saves.(_Fatherland).Read(0xc820578000, 0x7fecf4663c18, 0xc820022088, 0x0, 0x0)
        /root/gopath/src/github.com/ReversingSpace/dominions4.gamedata/saves/fatherland.go:364 +0x237c
main.(_GameWatcher).StartWatch(0xc8200e5938, 0xc8200d2e70, 0x2b, 0x7fecf464f780, 0xc8200aea60, 0x2, 0x0, 0x0)
        /root/gopath/src/github.com/blitzserver/blitzbackend/gamewatcher.go:93 +0x87e
created by main.(*ServerList).CreateServer
        /root/gopath/src/github.com/blitzserver/blitzbackend/serverlist.go:135 +0x1da7
